name: Offlinewhitelist
version: '${version}'
main: dev.hfdan.offlinewhitelist.Offlinewhitelist
api-version: 1.18
load: STARTUP
authors: [ HFDan ]
description: A plugin that allows using whitelists even when offline
